set(_CATKIN_CURRENT_PACKAGE "hri")
set(hri_VERSION "0.0.1")
set(hri_MAINTAINER "Pablo Lanillos <p.lanillos@tum.de>")
set(hri_PACKAGE_FORMAT "1")
set(hri_BUILD_DEPENDS "message_generation" "rospy")
set(hri_BUILD_EXPORT_DEPENDS "rospy" "message_runtime")
set(hri_BUILDTOOL_DEPENDS "catkin")
set(hri_BUILDTOOL_EXPORT_DEPENDS )
set(hri_EXEC_DEPENDS "rospy" "message_runtime")
set(hri_RUN_DEPENDS "rospy" "message_runtime")
set(hri_TEST_DEPENDS )
set(hri_DOC_DEPENDS )
set(hri_URL_WEBSITE "")
set(hri_URL_BUGTRACKER "")
set(hri_URL_REPOSITORY "")
set(hri_DEPRECATED "")